fix up package tarball upload step

diff --git a/.github/actions/prepare-package-tarball-if-version-changed/action.yml b/.github/actions/prepare-package-tarball-if-version-changed/action.yml
--- a/.github/actions/prepare-package-tarball-if-version-changed/action.yml
+++ b/.github/actions/prepare-package-tarball-if-version-changed/action.yml
@@ -40,46 +40,39 @@ runs:
     - name: Build package ${{ inputs.package_name }}
       if: steps.check.outputs.needs_publish == 'true' && inputs.needs_build == 'true'
       shell: bash
+      id: build
       run: bun run build --filter ${{ inputs.package_name }}
 
     - name: Assert dist/ directory exists
       if: steps.check.outputs.needs_publish == 'true'
       shell: bash
-      working-directory: ${{ inputs.package_path }}
-      run: |
-        if [ ! -d "${{ steps.tarball_name.outputs.tarball_name }}/dist" ]; then
-          echo "Error: Directory ${{ steps.tarball_name.outputs.tarball_name }}/dist does not exist"
-          exit 1
-        fi
-
-    - name: Print tarball gather details
-      if: steps.check.outputs.needs_publish == 'true' && inputs.needs_build == 'true'
-      shell: bash
       run: |
         echo "Current directory: $(pwd)"
+        echo "Package Path: ${{ inputs.package_path }}"
         echo "Tarball name: ${{ steps.tarball_name.outputs.tarball_name }}"
+        if [ ! -d "${{ inputs.package_path }}/dist" ]; then
+          echo "Error: Directory ${{ inputs.package_path }}/dist does not exist after build step"
+          exit 1
+        fi
 
     - name: Pack up package with Bun
       if: steps.check.outputs.needs_publish == 'true'
       shell: bash
-      working-directory: ${{ inputs.package_path }}
-      run: bun pm pack --quiet --filename ${{ steps.tarball_name.outputs.tarball_name }} --gzip-level 9
+      run: cd ${{ inputs.package_path }} && bun pm pack --filename ${{ steps.tarball_name.outputs.tarball_name }} --gzip-level 9
 
     - name: Assert tarball exists
       if: steps.check.outputs.needs_publish == 'true'
       shell: bash
-      working-directory: ${{ inputs.package_path }}
       run: |
-        if [ ! -f "${{ steps.tarball_name.outputs.tarball_name }}" ]; then
-          echo "Error: Tarball ${{ steps.tarball_name.outputs.tarball_name }} does not exist"
+        if [ ! -f "${{ inputs.package_path }}/${{ steps.tarball_name.outputs.tarball_name }}" ]; then
+          echo "Error: Tarball ${{ inputs.package_path }}/${{ steps.tarball_name.outputs.tarball_name }} does not exist"
           exit 1
         fi
 
     - name: Upload package artifact
       if: steps.check.outputs.needs_publish == 'true'
       uses: actions/upload-artifact@v6
-      working-directory: ${{ inputs.package_path }}
       with:
         name: ${{ steps.tarball_name.outputs.tarball_name }}
-        path: ${{ steps.tarball_name.outputs.tarball_name }}
+        path: ${{ inputs.package_path }}/${{ steps.tarball_name.outputs.tarball_name }}
         retention-days: 1
